#! /bin/sh -e

################################################################################
# Author:        Jean-Baptiste Quenot <jb.quenot@caraldi.com>
# Purpose:       Create packing list for jmeter
# Date Created:  2005-07-01 12:30:50
# Revision:      $Id: confstyle 130 2003-09-09 13:26:36Z jbq $
################################################################################

#
# This script creates pkg-plist in current directory.  It may be invoked as
# "sh admin/make-plist".  It assumes that port is already extracted by
# "make extract", as the list of files depends on every file that is getting
# installed.
#

set -e

WRKSRC=$(make -V WRKSRC)
DATAFILES=$(make -V DATAFILES)

makeit ()
{
    echo '@comment $FreeBSD: ports/www/resin2/pkg-plist,v 1.5 2005/02/24 22:27:52 hq Exp $'
    list_files $DATAFILES | xargs -I - echo %%DATADIR%%/-

    echo bin/jmeter

    list_dirs $DATAFILES | xargs -I - echo @dirrm %%DATADIR%%/-
    echo @dirrm %%DATADIR%%
}

list_files()
{
    for dir in $* ; do
        echo Looking in $WRKSRC/$dir 1>&2
        ( cd $WRKSRC && find -s $dir -type f -or -type l )
    done
}

list_dirs()
{
    for dir in $* ; do
        echo Looking in $WRKSRC/$dir 1>&2
        # Remove all empty dirs
        ( cd $WRKSRC && find -s $dir -type d -empty -delete )
        # List all directories
        ( cd $WRKSRC && find -s -d $dir -type d )
    done
}

makeit > pkg-plist
