#! /bin/sh -e

################################################################################
# File:          ant
# Author:        Jean-Baptiste Quenot <jb.quenot@caraldi.com>
# Purpose:       Invoke ant on the selected file within Nautilus
# Date Created:  2003-01-29 21:45:05
# CVS Id:        $Id: ant 406 2003-12-23 19:34:33Z jbq $
################################################################################

cd ${NAUTILUS_SCRIPT_CURRENT_URI#file://}
buildfile=$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
test -n "$buildfile" && exec zvt ant -buildfile $buildfile || exec zvt ant
