#! /bin/sh -e

################################################################################
# File:          cvs-update
# Author:        Jean-Baptiste Quenot <jb.quenot@caraldi.com>
# Purpose:       Update the selected directory with CVS within Nautilus
# Date Created:  2003-01-29 21:45:04
# CVS Id:        $Id: cvs-update 406 2003-12-23 19:34:33Z jbq $
################################################################################

dir=$NAUTILUS_SCRIPT_SELECTED_FILE_PATH
test -z $dir && dir=${NAUTILUS_SCRIPT_CURRENT_URI#file://}
cd $dir
exec zvt cvs -q update -d
