#! /bin/sh

doit() {
    for uri in $NAUTILUS_SCRIPT_SELECTED_URIS ; do
        file=${uri#file://}

        if test -f $file ; then
            remote-gvim $file
        fi
    done
}

doit >& /tmp/`basename $0`.log
