#! /bin/sh -e

################################################################################
# File:          backup-mail
# Author:        Jean-Baptiste Quenot
# Purpose:       Backup mail
# Date Created:  2003-07-09 18:57:11
# Revision:      $Id$
################################################################################

if test -z "$2" ; then
    echo "Usage: `basename $0` mail-file-or-dir backup-dir [basename]"
    exit 1
fi

SRC=$1
DST=$2
BASENAME=$3

dir=$SRC

if ! test -e $dir ; then
    echo "'"$dir"'" does not exist
    exit 1
fi

test -d $dir && dirname=$(basename $dir) || dirname=$dir
test -n "$BASENAME" && dirname=$BASENAME

destfile=$DST/$dirname-$(date "+%Y%m%d").tar.bz2
echo -n Backing up $dir as $destfile...
# Remove destfile when an error occurs to prevent truncated file
tar -c -f - $dir 2>/dev/null | bzip2 > $destfile || ( rm -f $destfile ; false )
echo " OK"
