#! /bin/sh -e

################################################################################
# File:          backup-sql
# Author:        Jean-Baptiste Quenot
# Purpose:       Backup MySQL databases
# Date Created:  2003-07-09 18:57:11
# Revision:      $Id$
################################################################################

DST=$1
shift
DATABASES=$1
shift

OPTIONS="--complete-insert"

for database in $DATABASES ; do
    # backup database
    echo mysqldump $OPTIONS $database
    mysqldump $OPTIONS $database \
    | bzip2 > $DST/$database-$(date "+%Y%m%d").sql.bz2
done
