#! /bin/sh -e

################################################################################
# File:          backup-svn
# Author:        Jean-Baptiste Quenot
# Purpose:       Backup SVN repositories
# Date Created:  2003-07-09 18:57:11
# Revision:      $Id$
################################################################################

if test -z "$2" ; then
    echo "Usage: `basename $0` svn-repos backup-dir [basename]"
    exit 1
fi

SRC=$1
DST=$2
BASENAME=$3

dir=$SRC

if ! test -d $dir ; then
    echo "'"$dir"'" does not exist
    exit 1
fi

TMPFILE=/tmp/`basename $0`.$$
dirname=$(basename $dir)
test -n "$BASENAME" && dirname=$BASENAME

# backup dir
destfile=$DST/$dirname-$(date "+%Y%m%d").bz2
echo -n Backing up $dir as $destfile...
svnadmin dump $dir 2> $TMPFILE | bzip2 > $destfile
echo " OK"

egrep -v "^* Dumped revision" < $TMPFILE || true
rm -f $TMPFILE
#done
