#! /bin/sh

set -e

MAXTEMPERATURE=$1

TEMPERATURE=$( lmmon -sp -i | sed -n 2p | cut -d/ -f1 | cut -dC -f 1 )

expr $TEMPERATURE '>' $MAXTEMPERATURE > /dev/null && \
    echo Temperature has reached ${TEMPERATURE}C
