#! /bin/sh -e

################################################################################
# File:          fortune-motd
# Author:        Jean-Baptiste Quenot <jb.quenot@caraldi.com>
# Purpose:       Have a funny welcome message
# Date Created:  2002-07-24 00:51:58
# CVS Id:        $Id: fortune-motd 356 2003-11-13 08:16:27Z jbq $
################################################################################

# Get the first line from current motd
head -1 < /etc/motd > /tmp/fortune.$$
echo >> /tmp/fortune.$$

# Add a fortune cookie
fortune $* >> /tmp/fortune.$$
echo >> /tmp/fortune.$$

# Add a greeting
echo "Welcome to $(uname)!" >> /tmp/fortune.$$

# Overwrite motd
cat /tmp/fortune.$$ > /etc/motd
rm -f /tmp/fortune.$$
