#! /bin/sh -e

# Configure kernel
make menuconfig

# Remove all previously compiled binaries
make clean

# Build dependencies
make dep

# Build and install kernel
make all install

# Build and install modules
make modules modules_install
