#! /bin/sh -e

DISK=$HOME/var/disk.img

if [ "$(uname)" = "FreeBSD" ] ; then
    test -e /dev/md0 || sudo mdconfig -a -t vnode -f $DISK -u 0
    sudo gbde attach /dev/md0 -l /etc/gbde/disk.img
    sudo mount -o suiddir -t ufs /dev/md0.bde $HOME/var/files
else
    DEV=${CRYPTDEV:-/dev/loop0}
    if [ "$(sudo losetup -f)" = "$DEV" ] ; then
        sudo losetup $DEV $DISK
    fi
    sudo cryptsetup luksOpen $DEV disk || true
    sudo mount -t ext3 /dev/mapper/disk $HOME/var/files
fi
