#! /bin/sh

################################################################################
# File:          pptp-started
# Author:        Jean-Baptiste Quenot
# Purpose:       Fancy wait until a default route has been setup
# Date Created:  2001-01-01 00:00:00
# Revision:      $Id: pptp-started 288 2003-10-10 07:44:17Z jbq $
################################################################################

#! /bin/sh

while [ 1 ]
do
	netstat -nr | grep ^default >& /dev/null && exit 0
	sleep 1
	echo -ne "."
	sleep 1
	echo -ne "."
	sleep 1
	echo -ne "."
	sleep 1
	echo -ne "\b \b"
	sleep 1
	echo -ne "\b \b"
	sleep 1
	echo -ne "\b \b"
done
