#! /usr/bin/env python

################################################################################
# Author:        Jean-Baptiste Quenot <jb.quenot@caraldi.com>
# Purpose:       Control tomcat process
# Date Created:  2005-01-21 15:43:37
# Revision:      $FreeBSD: ports/www/cocoon/files/cocoonctl,v 1.1 2004/07/01 22:30:19 glewis Exp $
################################################################################
# Copyright (c) 2004, Jean-Baptiste Quenot <jb.quenot@caraldi.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * The name of the contributors may not be used to endorse or promote products
#   derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################
#
# Files handled by this script (pid file, log files) must reside in a writable
# directory, ie the directory must be owned by the user running the program.
#

import caraldi, getopt, os, sys

args = {
    "LOG_FILE": "tomcat.log",
    "APP_NAME": "tomcat",
    "APP_HOME": os.environ['CATALINA_HOME'],
    "PID_FILE": "tomcat.pid",
    "COMMAND":  os.environ['CATALINA_HOME'] + "/bin/catalina.sh"
}

args_debug = ["jpda", "run"]
args["ARGS"] = ["run"]
script_debug = 0

def usage():
    print >> sys.stderr, "Usage: %s [-d|--debug] {start|stop|restart}" % sys.argv[0]

if __name__ == '__main__':
    opts, args['cmdargs'] = getopt.getopt (sys.argv[1:], 'dh', ['debug', 'help', "script-debug"])

    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit(1)
        if o in ("-d", "--debug"):
            args['ARGS'] = args_debug
        if o in ("--script-debug"):
            script_debug = 1

    if len(args['cmdargs']) != 1:
        usage()
        sys.exit(1)

    ctl = caraldi.DaemonCtl(args)

    if (script_debug):
        ctl.logger.setLevel(caraldi.DefaultLogger.DEBUG)

    if args['cmdargs'][0] == "start":
        ctl.start()

    elif args['cmdargs'][0] == "stop":
        ctl.stop()

    elif args['cmdargs'][0] == "restart":
        ctl.stop()
        ctl.start()

    else:
        usage()
        sys.exit(1)
