#! /bin/sh -e
#
# File:          update-ports
# Author:        Jean-Baptiste Quenot <jb.quenot@caraldi.com>
# Purpose:       Refresh the FreeBSD ports tree
# Date Created:  2003-06-29 11:12:39
# Revision:      $Id$
#
# Copyright (c) 2004, Jean-Baptiste Quenot <jb.quenot@caraldi.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * The name of the contributors may not be used to endorse or promote products
#   derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# PORTS_INDEX defaults to INDEX-5 on FreeBSD 5.x and INDEX on FreeBSD 4.x.  If
# you want to override the default value, please set an environment variable
# with this name.  Be careful to specify the same value as defined in
# pkgtools.conf.
#
# Example:
#   export PORTS_INDEX=/usr/ports/INDEX-5
# or
#   export PORTS_INDEX=/usr/ports/INDEX

if test -z "${PORTS_INDEX}" ; then
    OSVERSION=$(sysctl -n kern.osreldate)
    OSMAJORVERSION=$(echo $OSVERSION | sed -e 's/^\(.\).*$/\1/')
    if test "${OSVERSION%%4*}" = "" ; then
        PORTS_INDEX="/usr/ports/INDEX"
    else
        PORTS_INDEX="/usr/ports/INDEX-$OSMAJORVERSION"
    fi

    export PORTS_INDEX
fi

echo "Using INDEX file $PORTS_INDEX"

SUPFILE=/usr/share/examples/cvsup/ports-supfile
test -n "$1" && SUPFILE="$1"

LOGFILE=/tmp/`basename $0`.$$.log
LOGFILE2=/tmp/`basename $0`2.$$.log

# Update the ports tree
if which csup 2>&1 ; then
    CSUP=csup
else
    CSUP=cvsup
fi
if ! $CSUP -L 2 -h cvsup2.fr.FreeBSD.org -z -r 3 $SUPFILE | tee $LOGFILE ; then
    cat $LOGFILE 1>&2
    exit 1
fi

# Update INDEX
if which portindex >/dev/null 2>&1 ; then
    if ! test -e /var/db/portindex/portindex-cache.db ; then
        if ! cache-init -q 2>&1 | tee $LOGFILE2 ; then
            echo "cache-init returned status code $?"
            cat $LOGFILE2 1>&2
            exit 1
        fi
    elif ! cache-update -q < $LOGFILE 2>&1 | tee $LOGFILE2 ; then
        echo "cache-update returned status code $?"
        cat $LOGFILE2 1>&2
        exit 1
    fi
    rm -f $LOGFILE2
    if ! portindex -q -o $PORTS_INDEX 2>&1 | tee $LOGFILE ; then
        echo "portindex returned status code $?"
        cat $LOGFILE 1>&2
        exit 1
    fi
else
    if ! portsdb -U 2>&1 | tee $LOGFILE ; then
        echo "portsdb -U returned status code $?"
        cat $LOGFILE 1>&2
        exit 1
    fi
fi

# Update INDEX.db
if ! portsdb -u 2>&1 | tee $LOGFILE ; then
    echo "portsdb -u returned status code $?"
    cat $LOGFILE 1>&2
    exit 1
fi

# Record leaf packages
if which pkg_cutleaves >/dev/null 2>&1 ; then
    pkg_cutleaves -l > /tmp/pkg_listleaves.$$.txt && mv /tmp/pkg_listleaves.$$.txt /tmp/pkg_listleaves.txt
fi

# Record outdated ports
# Updates the package database and prints info to stderr
if ! portversion -v -l '<' > /tmp/portversion.$$.txt 2>$LOGFILE ; then
    cat $LOGFILE 1>&2
    exit 1
fi

mv /tmp/portversion.$$.txt /tmp/portversion.txt

rm -f $LOGFILE
