#! /bin/sh

test -h slides || (
  test "`uname`" = "Linux" && ln -s /usr/share/sgml/docbook/custom/slides/3.0b1/xsl slides && echo "Linked slides" || true
  test "`uname`" = "FreeBSD" && ln -s /usr/local/share/xsl/slides slides && echo "Linked slides" || true
)

test -h docbook || (
  test "`uname`" = "Linux" && test -e /usr/share/sgml/docbook/stylesheet/xsl/nwalsh && ln -s /usr/share/sgml/docbook/stylesheet/xsl/nwalsh docbook && echo "Linked docbook" || true
  test "`uname`" = "Linux" && test -e /usr/share/sgml/docbook/xsl-stylesheets && ln -s /usr/share/sgml/docbook/xsl-stylesheets docbook && echo "Linked docbook" || true
  test "`uname`" = "FreeBSD" && ln -s /usr/local/share/xsl/docbook && echo "Linked docbook" || true
)
