#! /bin/sh

set -e

WRKSRC=$(make -V WRKSRC)
COPYDIRS=$(make -V COPYDIRS)

makeit ()
{
    list_files | xargs -I - echo %%APP_NAME%%/-

    # libexec shared objects exist after make install
    echo %%APP_NAME%%/libexec/libresin.so
    echo %%APP_NAME%%/libexec/libresinssl.so

    echo etc/app-default.xml
    echo etc/rc.d/%%APP_NAME%%.sh
    echo sbin/%%APP_NAME%%ctl
    echo %%MOD_DIR%%/mod_caucho.so
    # Executed when *package* is installed, not the port
    echo %%APACHE%%@exec %%APXS%% -e -a -n caucho %f
    echo %%APACHE%%@unexec %%APXS%% -e -A -n caucho %f

    list_dirs | xargs -I - echo @dirrm %%APP_NAME%%/-
    echo @dirrm %%APP_NAME%%/libexec
    echo @dirrm %%APP_NAME%%

    # Inspired from misc/screen
    echo "@unexec if cmp -s %D/etc/%%APP_NAME%%.xml %D/etc/%%APP_NAME%%.xml-dist; \
then rm -f %D/etc/%%APP_NAME%%.xml; \
else echo If permanently deleting this package, \
%D/etc/%%APP_NAME%%.xml must be removed manually; fi"
    echo etc/%%APP_NAME%%.xml-dist
    echo "@exec if test -f %B/%%APP_NAME%%.xml ; \
then echo Keeping %B/%%APP_NAME%%.xml intact from previous installation; \
else cp %F %B/%%APP_NAME%%.xml; fi"
}

list_files()
{
    for dir in $COPYDIRS ; do
        ( cd $WRKSRC && find $dir -type f -or -type l )
    done
}

list_dirs()
{
    for dir in $COPYDIRS ; do
        # Remove dll first so that directories becoming empty are deleted
        ( cd $WRKSRC && find $dir -name '*.dll' -delete )
        ( cd $WRKSRC && find $dir -type d -empty -delete )
        ( cd $WRKSRC && find -d $dir -type d )
    done
}

makeit > pkg-plist
