#! /bin/sh -e

# `make' before issuing ./admin/make-plist to build needed resources

WRKSRC=$(make -V WRKSRC)
COPYDIRS=.
APP_NAME=eXist

exec > pkg-plist

cd ${WRKSRC}

find -s ${COPYDIRS} -type f | sed -e "s#^.#${APP_NAME}#"
find -s -d ${COPYDIRS} -type d | sed -e "s#^.#@dirrm ${APP_NAME}#"

dirhier() {
    local dir ddir
    dir=$1
    ddir=$(dirname $dir)
    if test "$ddir" != "." ; then
        echo $ddir
        dirhier $ddir
    fi
}

dirhiers() {
    for dir in ${COPYDIRS} ; do
        dirhier $dir
    done
}

dirhiers | uniq | sed -e "s#^#@dirrm ${APP_NAME}/#"
echo sbin/${APP_NAME}.sh
echo sbin/${APP_NAME}ctl
echo etc/rc.d/${APP_NAME}.sh
echo @dirrm ${APP_NAME}
