""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Author:        Jean-Baptiste Quenot <jb.quenot@caraldi.com>
" Purpose:       Define behaviour of ViM (versions 5 and 6 on Win32 and Unix)
" Revision:      $Id: vimrc 1001 2004-10-15 20:04:56Z jbq $
" Date Created:  2000-07-01 00:00:00
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set encoding=utf-8

" Don't try to be Vi-compliant
set nocompatible

" Make the backspace key wrap lines
set backspace=indent,eol,start

" Show current mode at the bottom left corner
set showmode

" Show size of visual selection
set showcmd

" Make selections behave like a WYSIWYG editor
" set selectmode=mouse,key,cmd

" Don't beep... please!
set visualbell

" Ignore case when searching 
set ignorecase

" If pattern contains upper case characters, don't ignore case
set smartcase

" If we have colors
if &t_Co > 2 || has("gui_running")
    " Turn on syntax highlighting
    syntax on

    " Highlight search pattern
    set hlsearch
endif

" Incremental search
set incsearch

" When switching buffers, do not warn if file is modified
set hidden

" show the line and column number of the cursor position
set ruler

" Show matching ()'s []'s {}'s
set showmatch

if version >= 600
	" Load folding rules
	runtime folding.vim
endif

" Load filetype-dependent auto commands
" Only do this part when compiled with support for autocommands.
if has("autocmd")
    runtime autocommands.vim
endif

" ~/.vim/doc/ (if found) contains documentation
" TODO how to get the location if this very file???
" % refers to the file edited by the user, <sfile> does not work
"exe "helptags " . "/home/jbq/usr/dot/vim/doc"

" Ignore those files when performing file name completion on command line
"set wildignore=*.class,*.java.html

if version >= 600
	" crontab -e does not work without that:
	set backupcopy=yes
endif

" Do not backup files (Some Linux distros use vimrc_example.vim)
set nobackup

" save buffer list (% option) does not work
" hilite search pattern on startup (h option removed)
" save all lines in registers to avoid data loss ("50 option removed)
set viminfo='20

iab JBQ Jean-Baptiste Quenot

set history=200

set nowrap
set sidescroll=5

if version >= 600
	set listchars+=precedes:<,extends:>
else
	set listchars+=extends:>
endif

" Restore modeline support
" By default disabled on Debian/Ubuntu for security
set modeline

dig Eu 8364

" Used with gf (open file under cursor)
set suffixesadd=.xml

" Set background to dark to have nicer syntax highlighting
set background=dark

" Since 6.3, xml foldmethod syntax is disabled
let g:xml_syntax_folding = 1

" Use this rather than plain environment variable because of launching mutt-ng
" in a terminal without real user login
let $PARINIT = 'rTbgqR B=.?_A_a Q=_s>|'

let g:jsx_ext_required = 0

execute pathogen#infect()

let g:ale_fixers = {'javascript': ['eslint_d'],}
let g:ale_completion_enabled = 1
let g:ale_linters = {'javascript': ['eslint_d'], 'typescript': ['eslint']}

nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)

" reformat text
vmap Q gq<cr>
