#! /bin/sh

set -e

PORT=numlockx

cleanup() {
    if test -d $PORT ; then
        if ! test "$1" = "-f" ; then
            echo -n "About to delete $(pwd)/$PORT.  Confirm? [y] "
            read answer
        fi

        test -z $answer && answer=y
        test $answer = y && rm -rf $PORT || false
    fi
}

cleanup $*
svn -q export http://svn.caraldi.com/trunk/Mk/$PORT $PORT
tar zcf $PORT.tgz --exclude=admin $PORT
cleanup $*
