#! /bin/sh -e

cd work
rm -f .build_done.cocoon-2.1.x._usr_local
rm -f .patch_done.cocoon-2.1.x._usr_local
rm -f .configure_done.cocoon-2.1.x._usr_local
cd cocoon-2.1.x
sh build.sh clean
svn revert *.sh
rm -f local.*.properties
